#
# Shane Canon scanon@lbl.gov
#
# Copyright 2015 The Regents of the University of California,
#                Lawrence Berkeley National Laboratory
#                United States Department of Energy
#                The DOE Systems Biology Knowledgebase (KBase)
# Made available under the KBase Open Source License
#

FROM nginx:1.9.2
MAINTAINER Shane Canon scanon@lbl.gov

COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf
