#!/bin/sh
#
# Build narrative image with this configuration
#
. ./site.cfg

cat << EOF > ./narrative/url.cfg 
SERVICESSL=${PUBLIC_ADDRESS}:8443
NARRSSL=${PUBLIC_ADDRESS}:6443
EOF
docker build -t kbase/narrative:latest narrative
