#!/bin/sh
#
# Build narrative image with this configuration
#
. ./site.cfg

cp -a ssl narrative/
cat << EOF > ./narrative/url.cfg 
SERVICESSL=$PUBLIC:8443
NARRSSL=$PUBLIC:6443
EOF
docker build -t kbase/narrative:latest narrative
