#!/bin/sh

if [ -e cluster.ini ] ; then
  echo "cluster.ini already exist!"
  exit
fi

. ./site.cfg

BASE=$(grep ^FROM Dockerfile|sed 's/FROM //')
docker run --rm $BASE cat /kb/deployment/deployment.cfg | \
	sed "s/=kbaseuserid/=$USER/"| \
	sed "s/=kbpassword/=$PASSWORD/"| \
	sed "s/public.hostname.org/${PUBLIC_ADDRESS}/g" | \
	sed "s|kbase/depl:latest|$IMAGE|g" \
	> cluster.ini
