#!/bin/sh

if [ -z $MYSERVICES ] ; then
  . ./site.cfg
  [ -z $IMAGE ] || IMAGE=kbase/depl:1.0
  docker run --rm -it --link mongo:mongo --entrypoint bash --env MYSERVICES=mongo --env PASSWD $IMAGE ./$0
else
  echo "Runing post"
  mv perl/List perl/List.dis
  /kb/runtime/bin/perl ./config/postprocess_Workspace
fi
