#!/bin/sh
. ./site.cfg
[ -z $IMAGE ] || IMAGE=kbase/depl:1.0

CG=dev

ARGS=" -d"
#ARGS=" -it --rm "

docker kill aweworker_$CG > /dev/null 2>&1
docker rm aweworker_$CG > /dev/null 2>&1

curl -s  http://localhost:8080/services/awe-api > /dev/null

docker run $ARGS \
        --name aweworker_$CG \
	$IMAGE aweworker $CG
